app:
  name: ${application.name}
  version: ${application.version}
  environment: dev
  description: ${application.description}
  pokeapi:
    url: https://pokeapi.co/api/v2
    read-timeout: 10s
    connect-timeout: 5s
    headers:
      user-agent: Micronaut-Pokemon-Client/1.0
      accept: application/json

micronaut:
  server:
    port: 9292
    context-path: /
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    services:
      pokeapi:
        url: https://pokeapi.co/
        path: api/v2